- name: Crear ruta y archivo local en el pod de Ansible
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Crear carpeta
      file:
        path: /tmp/ansible_demo
        state: directory

    - name: Crear archivo
      copy:
        content: "¡Hola! Este archivo fue creado por Ansible."
        dest: /tmp/ansible_demo/test.txt

    - name: Mostrar contenido del archivo
      command: cat /tmp/ansible_demo/test.txt
      register: contenido

    - name: Verificar contenido
      debug:
        var: contenido.stdout
