- name: Crear ruta y archivo en Windows
  hosts: win10
  gather_facts: no

  tasks:
    - name: Crear carpeta
      win_file:
        path: C:\Temp\MiCarpeta
        state: directory

    - name: Crear archivo si no existe
      win_file:
        path: C:\Temp\MiCarpeta\archivo.txt
        state: touch
