- name: Crear ruta y archivo en la VM
  hosts: all
  gather_facts: yes

  tasks:
    - name: Crear directorio /tmp/ejemplo si no existe
      file:
        path: /tmp/ejemplo
        state: directory
        mode: '0755'

    - name: Crear archivo archivo.txt si no existe
      copy:
        content: "Este es un archivo de prueba"
        dest: /tmp/ejemplo/archivo.txt
        force: no   # no sobreescribe si ya existe

    - name: Verificar si el archivo existe
      stat:
        path: /tmp/ejemplo/archivo.txt
      register: archivo_info

    - name: Mostrar resultado
      debug:
        msg: "El archivo existe: {{ archivo_info.stat.exists }}"
