- name: Listar pods en OpenShift
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Listar pods en el namespace default
      shell: oc get pods -n default
      register: pods

    - name: Mostrar resultado
      debug:
        var: pods.stdout_lines
