---
- name: Listar pods con autenticación usando credencial de OpenShift
  hosts: localhost
  gather_facts: false
  collections:
    - kubernetes.core

  tasks:
    - name: Autenticarse con OpenShift usando credencial
      k8s_auth:
        host: "{{ openshift_host }}"
        api_key: "{{ openshift_api_key }}"
        verify_ssl: false
      register: auth

    - name: Obtener pods del namespace default
      k8s_info:
        api_version: v1
        kind: Pod
        namespace: default
        kubeconfig: "{{ auth.kubeconfig }}"
      register: resultado

    - name: Mostrar lista de pods
      debug:
        msg: "{{ resultado.resources | map(attribute='metadata.name') | list }}"
