---
- name: Listar pods con credencial de OpenShift (Bearer Token)
  hosts: localhost
  gather_facts: false
  collections:
    - kubernetes.core

  vars:
    namespace: default

  tasks:
    - name: Obtener pods del namespace {{ namespace }}
      k8s_info:
        api_key: "{{ openshift_token }}"
        host: "{{ openshift_host }}"
        verify_ssl: false
        api_version: v1
        kind: Pod
        namespace: "{{ namespace }}"
      register: resultado

    - name: Mostrar lista de pods encontrados
      debug:
        msg: "{{ resultado.resources | map(attribute='metadata.name') | list }}"
