- name: Listar pods en OpenShift
  hosts: all
  gather_facts: no

  tasks:
    - name: Obtener pods del namespace 'default'
      kubernetes.core.k8s_info:
        api_version: v1
        kind: Pod
        namespace: default
      register: pods_encontrados

    - name: Mostrar lista de pods
      debug:
        var: pods_encontrados.resources
